version: '3.8'
services:
  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: abs-prometheus
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    - --storage.tsdb.retention.time=15d
    - --web.enable-lifecycle
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    - prometheus_data:/prometheus
    restart: unless-stopped
    networks:
    - abs-backend
  grafana:
    image: grafana/grafana:11.1.0
    container_name: abs-grafana
    environment:
    - GF_SECURITY_ADMIN_USER=
    - GF_SECURITY_ADMIN_PASSWORD=
    ports:
    - :3000
    depends_on:
    - prometheus
    restart: unless-stopped
    networks:
    - abs-backend
    - abs-frontend
volumes:
  prometheus_data: null
  grafana_data: null
